Nsng 567 fe finetuning
SlovakNationalGallery/stex-grid pull request #12
Opened 2024-06-20 07:59 UTC by igor-kamil

2024-06-25 11:45 UTC, FrantisekMichalSebestyen requested changes
Just marked few things:
- we should split sections from items on api
- display items based on the span-x and span-y order 
- also changes to editor are desirable

2024-06-25 11:45 UTC, FrantisekMichalSebestyen commented on tailwind.config.js
> +    require('@tailwindcss/typography'),
Could you explain what is the use case here?

2024-06-25 11:45 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +  const viewportHeight = window.innerHeight;
We need to rework this, so we dont use window -> so we can render this on server
+ pxValue is quite ambivalent name

2024-07-03 09:42 UTC, igor-kamil commented on tailwind.config.js
> +    require('@tailwindcss/typography'),
> The official Tailwind CSS Typography plugin provides a set of prose classes you can use to add beautiful typographic defaults to any vanilla HTML you don’t control, like HTML rendered from Markdown

we use it also elsewhere to set typographic behaviour on data parsed from markdown.
the default `prose` class already included proposed sizing, line-height and spacing.
I would prefer to use this package as it sets good standard for text in paragraphs. but the truth is that if necessary, the same can be achieved without the plugin. if you find this such a case @FrantisekMichalSebestyen , feel free to implement it in standalone task.

2024-07-03 09:46 UTC, igor-kamil commented
> Just marked few things:
> 
> * we should split sections from items on api

if you talk about avoiding the delay after switch language - I think turning on cache or SSR is better solution 

> * display items based on the span-x and span-y order

makes sense. but fixing this in admin takes just few minutes. and saves our time 😁 

> * also changes to editor are desirable

I agree 😉 

suggestions makes sense. but imho they are outside of the scope of this task and I suggest creating new tasks for them

2024-07-03 11:23 UTC, FrantisekMichalSebestyen requested changes

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on assets/img/info.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
@igor-kamil this should come from https://phosphoricons.com/ + fill and stroke should be set from outside

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on assets/img/logo.svg
> +<path d="M25.103 31.7737H38.1748V38.1445H22.4777V22.4777H38.1748V28.8485H25.103H25.003V28.9485V31.6737V31.7737H25.103ZM1 0.9H0.9V1V22.3777V22.4777H1H19.5223V38.1748H3.82521V25.103V25.003H3.72521H1H0.
👍

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +      class="absolute bottom-0 left-0 top-[80px] z-20 w-[calc(100vw-528px)] border-t-2 border-t-black bg-white"
```suggestion
      class="absolute bottom-0 left-0 top-20 z-20 w-[calc(100vw-528px)] border-t-2 border-t-black bg-white"
```

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +import { watch } from "vue";
```suggestion
```

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +const maxGridScrollValue = 1000;
move to consts?

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +  const viewportHeight = window.innerHeight;
did you create a task for this?

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +const translateShadowStyle = computed(() => {
this is weird as welll. Please create a task/fix now

2024-07-03 11:23 UTC, FrantisekMichalSebestyen commented on pages/index.vue
> +const sectionsData = computed(() => {
task/fix

2024-07-04 08:47 UTC, igor-kamil commented on pages/index.vue
> +  const viewportHeight = window.innerHeight;
https://jira.sng.sk/browse/NSNG-577

2024-07-04 08:59 UTC, igor-kamil commented on pages/index.vue
> +const sectionsData = computed(() => {
https://jira.sng.sk/browse/NSNG-579

2024-07-10 12:30 UTC, merged